// kubejsstudio recipes; re-apply merges by recipe id
ServerEvents.generateData('after_mods', event => {
    event.json('kubejsstudio:recipe/iron_nugget', {"type":"minecraft:smelting","ingredient":{"item":"oritech:small_iron_clump"},"result":{"id":"minecraft:iron_nugget"},"experience":0.1,"cookingtime":200})
    event.json('mysticalagriculture:recipe/machine_frame', {"type":"minecraft:crafting_shaped","category":"misc","pattern":["#A#","ABA","#A#"],"key":{"#":{"tag":"c:ingots/iron"},"A":{"item":"kubejs:metallic_essence"},"B":{"tag":"c:stones"}},"result":{"id":"mysticalagriculture:machine_frame","count":1}})
    event.json('enderio:recipe/sag_mill', {"type":"minecraft:crafting_shaped","category":"misc","pattern":["#A#","BCB","DED"],"key":{"#":{"tag":"c:gears/iron"},"A":{"item":"minecraft:flint"},"B":{"tag":"c:ingots/iron"},"C":{"item":"voidminers:aurantium_miner"},"D":{"tag":"c:obsidians"},"E":{"item":"minecraft:piston"}},"result":{"id":"enderio:sag_mill","count":1}})
    event.json('gateways:recipe/emerald_grove', {"type":"minecraft:crafting_shaped","group":"gateways","category":"misc","pattern":["###","#A#","###"],"key":{"#":{"tag":"minecraft:flowers"},"A":{"item":"voidminers:rubetine"}},"result":{"id":"gateways:gate_pearl","count":1,"components":{"gateways:gateway":"gateways:emerald_grove"}}})
    event.json('butchery:recipe/diamondhacksawrecipe', {"type":"minecraft:crafting_shaped","group":"hacksaw","category":"misc","pattern":["#AB","CDD"],"key":{"#":{"item":"kubejs:organic_essence"},"A":{"item":"kubejs:metallic_essence"},"B":{"item":"kubejs:precious_essence"},"C":{"item":"kubejs:earth_essence"},"D":{"tag":"c:gems/diamond"}},"result":{"id":"butchery:diamond_hacksaw","count":1}})
    event.json('kubejsstudio:recipe/red_heart_canister', {"type":"minecraft:smithing_transform","template":{"item":"bhc:canister"},"base":{"item":"bhc:red_heart"},"addition":{"item":"kubejs:living_essence"},"result":{"id":"bhc:red_heart_canister","count":1}})
    event.json('kubejsstudio:recipe/blue_heart_canister', {"type":"minecraft:smithing_transform","template":{"item":"bhc:canister"},"base":{"item":"bhc:blue_heart"},"addition":{"item":"advancednetherite:netherite_diamond_block"},"result":{"id":"bhc:blue_heart_canister","count":1}})
    event.json('kubejsstudio:recipe/green_heart_canister', {"type":"minecraft:smithing_transform","template":{"item":"bhc:canister"},"base":{"item":"bhc:green_heart"},"addition":{"item":"butchery:shulker_carcass"},"result":{"id":"bhc:green_heart_canister","count":1}})
    event.json('kubejsstudio:recipe/yellow_heart_canister', {"type":"minecraft:smithing_transform","template":{"item":"bhc:canister"},"base":{"item":"bhc:yellow_heart"},"addition":{"item":"allthemodium:allthemodium_apple"},"result":{"id":"bhc:yellow_heart_canister","count":1}})
    event.json('bhc:recipe/canister', {"type":"minecraft:crafting_shaped","group":"bhc:canister","category":"misc","pattern":[" # ","#A#"," # "],"key":{"#":{"item":"kubejs:living_essence"},"A":{"item":"justdirethings:potion_canister"}},"result":{"id":"bhc:canister","count":1}})
    event.json('functionalstorage:recipe/water_generator_upgrade', {"type":"minecraft:crafting_shaped","category":"misc","pattern":["#A#","#B#","#A#"],"key":{"#":{"tag":"c:stones"},"A":{"item":"mekanism:electric_pump"},"B":{"item":"minecraft:bucket"}},"result":{"id":"functionalstorage:water_generator_upgrade","count":1}})
    event.json('functionalstorage:recipe/dripping_upgrade', {"type":"minecraft:crafting_shaped","category":"misc","pattern":["#A#","BCB","#D#"],"key":{"#":{"tag":"c:stones"},"A":{"item":"minecraft:pointed_dripstone"},"B":{"item":"kubejs:nether_essence_block"},"C":{"item":"minecraft:cauldron"},"D":{"item":"minecraft:lava_bucket"}},"result":{"id":"functionalstorage:dripping_upgrade","count":1}})
    event.json('replicatemekanism:recipe/crafting/collapser/collapser_recipe', {"type":"minecraft:crafting_shaped","category":"misc","pattern":["#A#","BCB","#A#"],"key":{"#":{"item":"mekanism:alloy_reinforced"},"A":{"item":"mekanism:elite_control_circuit"},"B":{"tag":"c:ingots/osmium"},"C":{"item":"replication:disintegrator"}},"result":{"id":"replicatemekanism:collapser","count":1}})
    event.json('replicatemekanism:recipe/crafting/imaginator/imaginator_recipe', {"type":"minecraft:crafting_shaped","category":"misc","pattern":["#A#","BCB","#A#"],"key":{"#":{"item":"mekanism:alloy_reinforced"},"A":{"item":"mekanism:elite_control_circuit"},"B":{"tag":"c:ingots/osmium"},"C":{"item":"replication:replicator"}},"result":{"id":"replicatemekanism:imaginator","count":1}})
    event.json('replicatemekanism:recipe/crafting/imaginator/basic_imaginator_recipe', {"type":"minecraft:crafting_shaped","category":"misc","pattern":["#A#","BCB","#A#"],"key":{"#":{"item":"mekanism:alloy_atomic"},"A":{"item":"mekanism:ultimate_control_circuit"},"B":{"item":"replication:replica_ingot"},"C":{"item":"replicatemekanism:imaginator"}},"result":{"id":"replicatemekanism:imaginator_basic","count":1}})
    event.json('replicatemekanism:recipe/crafting/imaginator/advanced_imaginator_recipe', {"type":"minecraft:crafting_shaped","category":"misc","pattern":["#A#","BCB","#A#"],"key":{"#":{"item":"replicatemekanism:replica_alloy"},"A":{"item":"replicatemekanism:replica_control_circuit"},"B":{"item":"extendedcrafting:enhanced_ender_ingot"},"C":{"item":"replicatemekanism:imaginator_basic"}},"result":{"id":"replicatemekanism:imaginator_advanced","count":1}})
    event.json('replicatemekanism:recipe/crafting/imaginator/elite_imaginator_recipe', {"type":"minecraft:crafting_shaped","category":"misc","pattern":["#A#","BCB","#A#"],"key":{"#":{"item":"mekanism_extras:alloy_thermonuclear"},"A":{"item":"mekanism_extras:supreme_control_circuit"},"B":{"item":"extendedcrafting:black_iron_ingot"},"C":{"item":"replicatemekanism:imaginator_advanced"}},"result":{"id":"replicatemekanism:imaginator_elite","count":1}})
    event.json('replicatemekanism:recipe/crafting/imaginator/ultimate_imaginator_recipe', {"type":"minecraft:crafting_shaped","category":"misc","pattern":["#A#","BCB","#A#"],"key":{"#":{"item":"mekanism_extras:alloy_shining"},"A":{"item":"mekanism_extras:infinite_control_circuit"},"B":{"item":"allthemodium:vibranium_ingot"},"C":{"item":"replicatemekanism:imaginator_elite"}},"result":{"id":"replicatemekanism:imaginator_ultimate","count":1}})
    event.json('replicatemekanism:recipe/crafting/collapser/basic_collapser_recipe', {"type":"minecraft:crafting_shaped","category":"misc","pattern":["#A#","BCB","#A#"],"key":{"#":{"item":"mekanism:alloy_atomic"},"A":{"item":"mekanism:ultimate_control_circuit"},"B":{"tag":"c:ingots/osmium"},"C":{"item":"replicatemekanism:collapser"}},"result":{"id":"replicatemekanism:collapser_basic","count":1}})
    event.json('replicatemekanism:recipe/crafting/collapser/advanced_collapser_recipe', {"type":"minecraft:crafting_shaped","category":"misc","pattern":["#A#","BCB","#A#"],"key":{"#":{"item":"replicatemekanism:replica_alloy"},"A":{"item":"replicatemekanism:replica_control_circuit"},"B":{"item":"extendedcrafting:enhanced_ender_ingot"},"C":{"item":"replicatemekanism:collapser_basic"}},"result":{"id":"replicatemekanism:collapser_advanced","count":1}})
    event.json('replicatemekanism:recipe/crafting/collapser/elite_collapser_recipe', {"type":"minecraft:crafting_shaped","category":"misc","pattern":["#A#","BCB","#A#"],"key":{"#":{"item":"mekanism_extras:alloy_thermonuclear"},"A":{"item":"mekanism_extras:supreme_control_circuit"},"B":{"item":"extendedcrafting:black_iron_ingot"},"C":{"item":"replicatemekanism:collapser_advanced"}},"result":{"id":"replicatemekanism:collapser_elite","count":1}})
    event.json('replicatemekanism:recipe/crafting/collapser/ultimate_collapser_recipe', {"type":"minecraft:crafting_shaped","category":"misc","pattern":["#A#","BCB","#A#"],"key":{"#":{"item":"mekanism_extras:alloy_shining"},"A":{"item":"mekanism_extras:infinite_control_circuit"},"B":{"item":"allthemodium:vibranium_ingot"},"C":{"item":"replicatemekanism:collapser_elite"}},"result":{"id":"replicatemekanism:collapser_ultimate","count":1}})
    event.json('extendedcrafting:recipe/luminessence', {"type":"minecraft:crafting_shapeless","category":"misc","ingredients":[{"item":"kubejs:earth_essence_block"},{"item":"kubejs:metallic_essence_block"},{"item":"kubejs:precious_essence_block"},{"item":"kubejs:nether_essence_block"},{"item":"mysticalagriculture:inferium_block"},{"item":"kubejs:organic_essence_block"},{"item":"kubejs:ender_essence_block"},{"item":"kubejs:living_essence_block"},{"item":"voidminers:citrinetine"}],"result":{"id":"extendedcrafting:luminessence","count":2}})
    event.json('mekanism:recipe/combiner', {"type":"minecraft:crafting_shaped","category":"misc","pattern":["#A#","BCB","#A#"],"key":{"#":{"item":"mekanism_extras:alloy_thermonuclear"},"A":{"item":"mekanism_extras:supreme_control_circuit"},"B":{"tag":"mekanism:stone_crafting_materials"},"C":{"item":"mekanism:steel_casing"}},"result":{"id":"mekanism:combiner","count":1}})
    event.json('logisticsnetworks:recipe/logistics_node', {"type":"minecraft:crafting_shaped","category":"misc","pattern":["#A#","BCB","#D#"],"key":{"#":{"item":"mekanism_extras:alloy_thermonuclear"},"A":{"item":"minecraft:redstone_block"},"B":{"item":"minecraft:hopper"},"C":{"item":"minecraft:ender_eye"},"D":{"item":"minecraft:redstone_torch"}},"result":{"id":"logisticsnetworks:logistics_node","count":1}})
})
ServerEvents.recipes(event => {
    event.remove({ id: 'kubejsstudio:organic_void' })
    event.remove({ id: 'cyclic:uncrafter' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/aluminum' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/amethyst' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/armadillo' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/awakened_draconium' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/blaze' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/brass' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/breeze' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/bronze' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/certus_quartz' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/chicken' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/coal' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/conductive_alloy' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/constantan' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/copper' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/copper_alloy' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/coral' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/cow' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/creeper' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/dark_steel' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/deepslate' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/diamond' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/draconium' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/dragon_egg' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/dye' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/electrum' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/emerald' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/end' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/end_steel' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/enderman' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/energetic_alloy' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/energized_steel' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/experience' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/fiery_ingot' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/fish' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/fluix' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/fluorite' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/ghast' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/glowstone' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/gold' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/grains_of_infinity' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/honey' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/ice' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/invar' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/iridium' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/iron' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/knightmetal' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/lapis_lazuli' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/zombie' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/zinc' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/wood' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/blazing_crystal' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/dirt' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/lead' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/nature' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/nether' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/nether_quartz' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/nether_star' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/netherite' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/neutronium' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/nickel' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/niotic_crystal' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/nitro_crystal' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/obsidian' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/peridot' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/pig' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/prismarine' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/rabbit' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/redstone_alloy' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/refined_obsidian' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/sapphire' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/sheep' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/skeleton' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/soularium' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/spider' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/squid' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/steeleaf' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/tin' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/turtle' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/uranium' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/stone' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/sky_stone' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/refined_glowstone' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/redstone' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/ironwood' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/osmium' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/phantom' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/platinum' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/pulsating_alloy' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/ruby' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/sculk' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/silicon' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/silver' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/slime' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/soulium' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/spirited_crystal' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/steel' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/sulfur' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/uraninite' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/vibrant_alloy' })
    event.remove({ id: 'mysticalagriculture:seed/infusion/wither_skeleton' })
    event.remove({ id: 'mysticalagradditions:essence/awakened_draconium_nugget' })
    event.remove({ id: 'mysticalagradditions:essence/dragon_egg_chunk' })
    event.remove({ id: 'mysticalagradditions:essence/dragon_head' })
    event.remove({ id: 'mysticalagradditions:essence/nether_star_shard' })
    event.remove({ id: 'mysticalagradditions:essence/neutron_nugget' })
    event.remove({ id: 'mysticalagradditions:essence/nitro_crystal' })
    event.remove({ id: 'mysticalagriculture:essence/appliedenergistics2/calculation_press' })
    event.remove({ id: 'mysticalagriculture:essence/appliedenergistics2/certus_quartz' })
    event.remove({ id: 'mysticalagriculture:essence/appliedenergistics2/certus_quartz_dust' })
    event.remove({ id: 'mysticalagriculture:essence/appliedenergistics2/engineering_press' })
    event.remove({ id: 'mysticalagriculture:essence/appliedenergistics2/fluix' })
    event.remove({ id: 'mysticalagriculture:essence/appliedenergistics2/logic_press' })
    event.remove({ id: 'mysticalagriculture:essence/appliedenergistics2/sky_stone' })
    event.remove({ id: 'mysticalagriculture:essence/common/brass_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/common/constantan_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/common/graphite_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/common/iridium_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/common/nickel_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/common/platinum_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/common/saltpeter' })
    event.remove({ id: 'mysticalagriculture:essence/common/silver_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/common/sulfur' })
    event.remove({ id: 'mysticalagriculture:essence/common/aluminum_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/common/bronze_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/common/electrum_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/common/invar_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/common/lead_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/common/niter' })
    event.remove({ id: 'mysticalagriculture:essence/common/rubber' })
    event.remove({ id: 'mysticalagriculture:essence/common/silicon' })
    event.remove({ id: 'mysticalagriculture:essence/common/steel_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/common/tin_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/common/uranium_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/common/zinc_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/enderio/conductive_alloy_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/enderio/copper_alloy_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/enderio/dark_steel_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/enderio/end_steel_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/enderio/energetic_alloy_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/enderio/grains_of_infinity' })
    event.remove({ id: 'mysticalagriculture:essence/enderio/pulsating_alloy_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/enderio/redstone_alloy_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/enderio/soularium_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/enderio/vibrant_alloy_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/ender_eye' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/ender_pearl' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/enderman' })
    event.remove({ id: 'mysticalagriculture:essence/appliedenergistics2/fluix_dust' })
    event.remove({ id: 'mysticalagriculture:essence/appliedenergistics2/silicon_press' })
    event.remove({ id: 'mysticalagriculture:essence/draconicevolution/draconium_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/gems/apatite' })
    event.remove({ id: 'mysticalagriculture:essence/gems/peridot' })
    event.remove({ id: 'mysticalagriculture:essence/gems/ruby' })
    event.remove({ id: 'mysticalagriculture:essence/gems/sapphire' })
    event.remove({ id: 'mysticalagriculture:essence/mekanism/fluorite' })
    event.remove({ id: 'mysticalagriculture:essence/mekanism/osmium_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/mekanism/refined_glowstone_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/mekanism/refined_obsidian_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/acacia_log' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/acacia_sapling' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/amethyst' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/andesite' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/apple' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/armadillo_scute' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/arrow' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/bamboo' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/basalt' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/beef' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/beetroot' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/birch_log' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/birch_sapling' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/black_concrete' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/black_dye' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/blackstone' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/blaze_rod' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/blue_concrete' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/blue_dye' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/bone' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/brain_coral' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/brain_coral_block' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/brain_coral_fan' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/breeze_rod' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/brown_concrete' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/brown_mushroom' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/bubble_coral' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/bubble_coral_block' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/bubble_coral_fan' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/cactus' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/calcite' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/carrot' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/charcoal' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/cherry_log' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/cherry_sapling' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/chicken' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/chorus_fruit' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/clay_ball' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/coal' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/cobbled_deepslate' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/cobblestone' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/cocoa_beans' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/cod' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/copper_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/creeper_head' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/crimson_fungus' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/crimson_nylium' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/brown_dye' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/crimson_stem' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/cyan_concrete' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/cyan_dye' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/dark_oak_log' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/dark_oak_sapling' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/deepslate' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/diamond' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/diorite' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/dirt' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/dripstone' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/egg' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/emerald' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/end_stone' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/experience_droplet' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/feather' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/fire_coral' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/fire_coral_block' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/fire_coral_fan' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/flint' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/ghast_tear' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/glow_ink_sac' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/glowstone_dust' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/gold_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/granite' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/grass_block' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/gray_concrete' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/gravel' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/gray_dye' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/green_concrete' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/green_dye' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/gunpowder' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/heart_of_the_sea' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/honey_bottle' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/honeycomb' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/horn_coral' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/horn_coral_block' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/horn_coral_fan' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/ice' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/ink_sac' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/iron_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/jungle_log' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/jungle_sapling' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/kelp' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/lapis_lazuli' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/lava_bucket' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/leather' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/light_blue_concrete' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/light_blue_dye' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/light_gray_concrete' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/light_gray_dye' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/lily_pad' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/lime_concrete' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/lime_dye' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/magenta_concrete' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/magenta_dye' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/magma_cream' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/mangrove_log' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/mangrove_propagule' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/melon' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/milk_bucket' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/mud' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/music_disc_11' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/music_disc_13' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/music_disc_5' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/music_disc_blocks' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/music_disc_cat' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/music_disc_chirp' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/music_disc_creator' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/music_disc_creator_music_box' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/music_disc_far' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/music_disc_mall' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/music_disc_mellohi' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/music_disc_otherside' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/music_disc_pigstep' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/music_disc_precipice' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/music_disc_relic' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/music_disc_stal' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/music_disc_strad' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/music_disc_wait' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/music_disc_ward' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/mutton' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/mycelium' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/nautilus_shell' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/nether_bricks' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/nether_wart' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/netherite_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/netherrack' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/oak_log' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/oak_sapling' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/obsidian' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/orange_concrete' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/orange_dye' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/packed_ice' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/phantom_membrane' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/pink_concrete' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/pink_dye' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/podzol' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/pointed_dripstone' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/poisonous_potato' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/porkchop' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/potato' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/prismarine_crystals' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/prismarine_shard' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/pufferfish' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/pumpkin' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/purple_concrete' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/purple_dye' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/purpur_block' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/quartz' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/rabbit' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/rabbit_foot' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/rabbit_hide' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/red_concrete' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/red_dye' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/red_mushroom' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/red_sand' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/redstone' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/rotten_flesh' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/salmon' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/sand' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/sculk' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/sculk_catalyst' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/sculk_sensor' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/sculk_shrieker' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/sculk_vein' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/slime_ball' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/snow_block' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/soul_sand' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/soul_soil' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/spider_eye' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/spruce_log' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/spruce_sapling' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/stone' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/string' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/sugar_cane' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/tropical_fish' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/tube_coral' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/tube_coral_block' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/tube_coral_fan' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/tuff' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/turtle_scute' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/vine' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/warped_fungus' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/warped_nylium' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/warped_stem' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/water_bucket' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/wheat' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/white_concrete' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/skeleton_skull' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/white_dye' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/wither_skeleton_skull' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/yellow_concrete' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/yellow_dye' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/zombie_head' })
    event.remove({ id: 'mysticalagriculture:essence/minecraft/white_wool' })
    event.remove({ id: 'mysticalagriculture:essence/mysticalagriculture/soulium_dust' })
    event.remove({ id: 'mysticalagriculture:essence/powah/blazing_crystal' })
    event.remove({ id: 'mysticalagriculture:essence/powah/energized_steel' })
    event.remove({ id: 'mysticalagriculture:essence/powah/niotic_crystal' })
    event.remove({ id: 'mysticalagriculture:essence/powah/spirited_crystal' })
    event.remove({ id: 'mysticalagriculture:essence/powah/uraninite' })
    event.remove({ id: 'mysticalagriculture:essence/twilightforest/fiery_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/twilightforest/ironwood_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/twilightforest/knightmetal_ingot' })
    event.remove({ id: 'mysticalagriculture:essence/twilightforest/steeleaf_ingot' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/air' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/aluminum' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/amethyst' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/apatite' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/armadillo' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/awakened_draconium' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/blaze' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/blazing_crystal' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/brass' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/breeze' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/bronze' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/certus_quartz' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/chicken' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/coal' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/conductive_alloy' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/constantan' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/copper' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/copper_alloy' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/coral' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/cow' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/creeper' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/dark_steel' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/deepslate' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/diamond' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/dirt' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/draconium' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/dragon_egg' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/dye' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/earth' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/electrum' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/emerald' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/end' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/end_steel' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/energetic_alloy' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/energized_steel' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/experience' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/fiery_ingot' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/fire' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/fish' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/fluix' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/fluorite' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/ghast' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/glowstone' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/gold' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/grains_of_infinity' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/graphite' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/honey' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/ice' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/inferium' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/invar' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/iridium' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/iron' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/ironwood' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/knightmetal' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/lapis_lazuli' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/lead' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/nature' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/nether' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/nether_quartz' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/nether_star' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/netherite' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/neutronium' })
    event.remove({ id: 'jdte:greenhouse' })
    event.remove({ id: 'mekmm:compat/mysticalagradditions/planting/nether_star' })
    event.remove({ id: 'mysticalagriculture:blazegold_seeds_reprocessor' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/nickel' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/niotic_crystal' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/nitro_crystal' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/obsidian' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/osmium' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/peridot' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/phantom' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/pig' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/platinum' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/prismarine' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/pulsating_alloy' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/rabbit' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/redstone' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/redstone_alloy' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/refined_glowstone' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/refined_obsidian' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/rubber' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/ruby' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/saltpeter' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/sapphire' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/sculk' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/sheep' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/silicon' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/silver' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/skeleton' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/sky_stone' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/slime' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/soularium' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/soulium' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/spider' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/spirited_crystal' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/squid' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/steel' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/steeleaf' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/stone' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/sulfur' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/tin' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/turtle' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/uraninite' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/uranium' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/vibrant_alloy' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/water' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/wither_skeleton' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/wood' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/zinc' })
    event.remove({ id: 'mysticalagriculture:seed/reprocessor/zombie' })
    event.remove({ id: 'mysticalagriculture:seed_reprocessor' })
    event.shaped('minecraft:cobblestone', ['#A#', 'ABA', '#A#'], { '#': 'minecraft:dirt', 'A': 'kubejs:earth_essence', 'B': 'minecraft:oak_log' }).id('kubejsstudio:cobblestone')
    event.shaped('minecraft:coal_ore', ['###', '#A#', '###'], { '#': 'minecraft:stone', 'A': '#c:storage_blocks/charcoal' }).id('kubejsstudio:coal_ore')
    event.shaped('kubejs:metallic_essence', ['###', '#A#', '###'], { '#': 'kubejs:earth_essence', 'A': 'minecraft:coal_ore' }).id('kubejsstudio:metallic_essence')
    event.shaped(Item.of('kubejs:metallic_essence', 9), ['#'], { '#': 'kubejs:metallic_essence_block' }).id('kubejsstudio:metallic_essence_from_block')
    event.shaped('oritech:small_iron_clump', ['###', '###', '###'], { '#': 'kubejs:metallic_essence' }).id('kubejsstudio:small_iron_clump')
    event.shaped(Item.of('kubejs:organic_essence', 9), ['#'], { '#': 'kubejs:organic_essence_block' }).id('kubejsstudio:organic_essence_from_block')
    event.shaped('kubejs:organic_essence', ['#A#', 'ABA', '#A#'], { '#': 'minecraft:oak_sapling', 'A': 'kubejs:earth_essence', 'B': 'minecraft:apple' }).id('kubejsstudio:organic_essence')
    event.shaped('minecraft:lily_pad', ['###', '# #', '###'], { '#': 'kubejs:organic_essence' }).id('kubejsstudio:lily_pad')
    event.shaped('farmersdelight:rich_soil', ['###', '###', '###'], { '#': 'kubejs:organic_essence' }).id('kubejsstudio:biomass')
    event.remove({ id: 'oritech:crafting/alloy/steel' })
    event.shaped('minecraft:iron_ore', ['###', 'ABA', '###'], { '#': 'kubejs:metallic_essence', 'A': 'minecraft:iron_ingot', 'B': 'minecraft:stone' }).id('kubejsstudio:iron_ore')
    event.shaped('mekanism:nugget_osmium', ['#A#', 'ABA', '#A#'], { '#': 'oritech:nickel_nugget', 'A': 'mysticalagriculture:machine_frame', 'B': 'voidminers:rubetine' }).id('kubejsstudio:osmium_nugget')
    event.shaped('oritech:nickel_nugget', ['#A#', 'BCB', '#A#'], { '#': 'oritech:iron_clump', 'A': 'kubejs:metallic_essence', 'B': 'kubejs:organic_essence', 'C': 'voidminers:rubetine' }).id('kubejsstudio:nickel_nugget')
    event.shaped('mekanism:nugget_osmium', ['#A#', 'ABA', '#A#'], { '#': 'oritech:nickel_nugget', 'A': 'mysticalagriculture:machine_frame', 'B': 'voidminers:rubetine' }).id('kubejsstudio:nugget_osmium')
    event.shaped('4x voidminers:rubetine', ['#AB', '#CB', '#AB'], { '#': 'kubejs:metallic_essence', 'A': 'minecraft:iron_ore', 'B': 'kubejs:organic_essence', 'C': 'mysticalagriculture:machine_frame' }).id('kubejsstudio:rubetine')
    event.shaped(Item.of('voidminers:solar_rubetine', 4), ['#A#', 'ABA', '#A#'], { '#': 'voidminers:rubetine', 'A': 'mekanism:nugget_osmium', 'B': 'oritech:nickel_ingot' }).id('kubejsstudio:solar_rubetine')
    event.shaped('minecraft:gravel', ['###', '#A#', '###'], { '#': 'minecraft:dirt', 'A': 'kubejs:metallic_essence' }).id('kubejsstudio:gravel')
    event.shaped('minecraft:sand', ['###', '#A#', '###'], { '#': 'minecraft:gravel', 'A': 'kubejs:metallic_essence' }).id('kubejsstudio:sand')
    event.remove({ id: 'voidminers:rubetine' })
    event.remove({ id: 'voidminers:solar_rubetine' })
    event.shaped('6x kubejs:precious_essence', ['BBB', '#A#', 'BBB'], { '#': 'allthecompressed:glass_1x', 'B': 'minecraft:glass', 'A': 'voidminers:rubetine' }).id('kubejsstudio:precious_essence')
    event.shapeless('minecraft:redstone', ['kubejs:precious_essence', 'kubejs:precious_essence', 'kubejs:precious_essence', 'minecraft:red_dye']).id('kubejsstudio:redstone')
    event.shapeless('minecraft:rose_bush', ['voidminers:rubetine', 'kubejs:organic_essence', 'voidminers:rubetine', 'kubejs:organic_essence', 'kubejs:earth_essence', 'kubejs:organic_essence', 'voidminers:rubetine', 'kubejs:organic_essence', 'voidminers:rubetine']).id('kubejsstudio:rose_bush')
    event.shapeless('oritech:nickel_ore', ['kubejs:metallic_essence', 'minecraft:iron_ore', 'kubejs:metallic_essence', 'minecraft:iron_ore', 'minecraft:gravel', 'minecraft:iron_ore', 'kubejs:metallic_essence', 'minecraft:iron_ore', 'kubejs:metallic_essence']).id('kubejsstudio:nickel_ore')
    event.shaped('mekanism:osmium_ore', ['###', 'ABA', '###'], { '#': 'kubejs:metallic_essence', 'A': 'mekanism:ingot_osmium', 'B': 'minecraft:gold_ore' }).id('kubejsstudio:osmium_ore')
    event.shaped('minecraft:gold_nugget', ['#A#', 'ABA', '#A#'], { '#': 'kubejs:metallic_essence', 'A': 'kubejs:precious_essence', 'B': 'mekanism:nugget_osmium' }).id('kubejsstudio:gold_nugget')
    event.shaped('minecraft:gold_ore', ['###', 'ABA', '###'], { '#': 'kubejs:precious_essence', 'A': 'minecraft:gold_ingot', 'B': 'minecraft:glowstone' }).id('kubejsstudio:gold_ore')
    event.shaped('minecraft:redstone_ore', ['#A#', 'ABA', '#A#'], { '#': 'kubejs:precious_essence', 'A': 'minecraft:redstone_block', 'B': 'minecraft:gold_ore' }).id('kubejsstudio:redstone_ore')
    event.shaped('oritech:copper_nugget', ['#A#', 'ABA', '#A#'], { '#': 'kubejs:metallic_essence', 'A': 'oritech:nickel_nugget', 'B': 'kubejs:earth_essence' }).id('kubejsstudio:copper_nugget')
    event.shaped('minecraft:copper_ore', ['###', 'ABA', '###'], { '#': 'kubejs:metallic_essence', 'A': 'minecraft:copper_ingot', 'B': 'oritech:nickel_ore' }).id('kubejsstudio:copper_ore')
    event.shaped('minecraft:glowstone_dust', ['###', 'ABA', '###'], { '#': 'kubejs:precious_essence', 'A': 'minecraft:yellow_dye', 'B': 'minecraft:redstone' }).id('kubejsstudio:glowstone_dust')
    event.shaped('minecraft:grass_block', ['###', 'AAA', '###'], { '#': 'minecraft:dirt', 'A': 'kubejs:organic_essence' }).id('kubejsstudio:grass_block')
    event.shaped('minecraft:lapis_ore', ['#A#', 'ABA', '#A#'], { '#': 'kubejs:precious_essence', 'A': 'minecraft:lapis_block', 'B': 'minecraft:redstone_ore' }).id('kubejsstudio:lapis_ore')
    event.shaped('minecraft:cornflower', ['###'], { '#': 'kubejs:organic_essence' }).id('kubejsstudio:cornflower')
    event.shaped('minecraft:dandelion', ['###'], { '#': 'kubejs:organic_essence' }).id('kubejsstudio:dandelion')
    event.shaped('actuallyadditions:flax_seeds', ['# #', '#A#', '###'], { '#': 'kubejs:organic_essence', 'A': 'farmersdelight:rich_soil' }).id('kubejsstudio:flax_seeds')
    event.shaped('minecraft:wheat_seeds', ['###', '###', '#A#'], { '#': 'kubejs:organic_essence', 'A': 'farmersdelight:rich_soil' }).id('kubejsstudio:wheat_seeds')
    event.shaped('minecraft:diamond_ore', ['#A#', 'ABA', '#A#'], { '#': 'minecraft:redstone_ore', 'A': 'minecraft:lapis_ore', 'B': 'minecraft:diamond_block' }).id('kubejsstudio:diamond_ore')
    event.shaped('minecraft:diamond', ['#A#', 'ABA', '#A#'], { '#': 'minecraft:redstone_ore', 'A': 'minecraft:gold_ore', 'B': 'mekanism:osmium_ore' }).id('kubejsstudio:diamond')
    event.remove({ id: 'dankstorage:dank_1' })
    event.shaped('dankstorage:dank_1', ['###', '#A#', '###'], { '#': '#c:storage_blocks/charcoal', 'A': 'minecraft:barrel' }).id('kubejsstudio:dank_1')
    event.remove({ id: 'allthemodium:teleport_pad' })
    event.shaped('minecraft:lava_bucket', ['#A#', 'BCB', '#A#'], { '#': 'justdirethings:coal_t1', 'A': 'minecraft:glowstone_dust', 'B': 'minecraft:redstone', 'C': 'minecraft:bucket' }).id('kubejsstudio:lava_bucket')
    event.shaped('minecraft:water_bucket', ['#A#', 'BCB', '#A#'], { '#': 'minecraft:lily_pad', 'A': 'minecraft:glowstone_dust', 'B': 'minecraft:redstone', 'C': 'minecraft:bucket' }).id('kubejsstudio:water_bucket')
    event.remove({ id: 'curvy_pipes:item_s2t' })
    event.shapeless(Item.of('curvy_pipes:tiny_item_pipe', 4), ['kubejs:metallic_essence', 'minecraft:iron_nugget', 'kubejs:metallic_essence', 'minecraft:iron_nugget', 'minecraft:chest', 'minecraft:iron_nugget', 'kubejs:metallic_essence', 'minecraft:iron_nugget', 'kubejs:metallic_essence']).id('kubejsstudio:tiny_item_pipe')
    event.shapeless('2x minecraft:lapis_lazuli', ['kubejs:precious_essence', 'kubejs:precious_essence', 'kubejs:precious_essence', 'minecraft:blue_dye', 'minecraft:redstone', 'minecraft:blue_dye', 'kubejs:precious_essence', 'kubejs:precious_essence', 'kubejs:precious_essence']).id('kubejsstudio:lapis_lazuli')
    event.remove({ id: 'jdte:underclock_upgrade' })
    event.remove({ id: 'actuallyadditions:laser/nether_wart' })
    event.shaped('minecraft:nether_wart', ['###', 'ABA', '###'], { '#': 'kubejs:nether_essence', 'A': 'minecraft:redstone', 'B': 'minecraft:red_mushroom' }).id('kubejsstudio:nether_wart')
    event.shaped('minecraft:red_mushroom', ['###', 'ABA', '###'], { '#': 'kubejs:organic_essence', 'A': 'minecraft:red_dye', 'B': 'kubejs:earth_essence' }).id('kubejsstudio:red_mushroom')
    event.shaped('minecraft:obsidian', ['###', 'ABC', '###'], { '#': 'kubejs:nether_essence', 'A': 'minecraft:water_bucket', 'B': 'voidminers:rubetine', 'C': 'minecraft:lava_bucket' }).id('kubejsstudio:obsidian')
    event.shaped(Item.of('kubejs:nether_essence', 9), ['#'], { '#': 'kubejs:nether_essence_block' }).id('kubejsstudio:nether_essence_from_block')
    event.shaped('minecraft:blaze_powder', ['#A#', 'ABA', '#A#'], { '#': 'kubejs:nether_essence', 'A': 'kubejs:living_essence', 'B': 'voidminers:rubetine' }).id('kubejsstudio:blaze_powder')
    event.shaped('minecraft:blaze_rod', ['#A#', 'A#A', '#A#'], { '#': 'minecraft:blaze_powder', 'A': 'voidminers:aurantium' }).id('kubejsstudio:blaze_rod')
    event.shaped('4x minecraft:quartz', ['#A#', 'ABA', '#A#'], { '#': 'kubejs:precious_essence', 'A': 'kubejs:nether_essence', 'B': 'allthecompressed:glass_1x' }).id('kubejsstudio:quartz')
    event.shaped('minecraft:mud', ['#A'], { '#': 'farmersdelight:rich_soil', 'A': 'minecraft:sand' }).id('kubejsstudio:mud')
    event.shaped('minecraft:sugar_cane', ['###', 'AAA', '###'], { '#': 'kubejs:organic_essence', 'A': 'minecraft:glass' }).id('kubejsstudio:sugar_cane')
    event.shaped('actuallyadditions:black_quartz', ['##', '#A'], { '#': 'kubejs:precious_essence', 'A': 'minecraft:black_dye' }).id('kubejsstudio:black_quartz')
    event.remove({ id: 'justdirethings:paradoxmachine' })
    event.remove({ id: 'modularrouters:player_module' })
    event.shaped(Item.of('mysticalagriculture:machine_frame', 6), ['#A#'], { '#': 'mysticalagriculture:machine_frame', 'A': 'minecraft:copper_block' }).id('kubejsstudio:machine_frame_dupe')
    event.remove({ id: 'actuallyadditions:crusher' })
    event.remove({ id: 'actuallyadditions:crusher_double' })
    event.remove({ id: 'actuallyadditions:crushing/allium' })
    event.remove({ id: 'actuallyadditions:crushing/azure_bluet' })
    event.remove({ id: 'actuallyadditions:crushing/black_quartz_ore' })
    event.remove({ id: 'actuallyadditions:crushing/blaze_rod' })
    event.remove({ id: 'actuallyadditions:crushing/blue_orchid' })
    event.remove({ id: 'actuallyadditions:crushing/bone' })
    event.remove({ id: 'actuallyadditions:crushing/coal_block' })
    event.remove({ id: 'actuallyadditions:crushing/cobblestone' })
    event.remove({ id: 'actuallyadditions:crushing/copper_ore' })
    event.remove({ id: 'actuallyadditions:crushing/cornflower' })
    event.remove({ id: 'actuallyadditions:crushing/deepslate_coal_ore' })
    event.remove({ id: 'actuallyadditions:crushing/deepslate_diamond_ore' })
    event.remove({ id: 'actuallyadditions:crushing/deepslate_gold_ore' })
    event.remove({ id: 'actuallyadditions:crushing/deepslate_emerald_ore' })
    event.remove({ id: 'actuallyadditions:crushing/deepslate_iron_ore' })
    event.remove({ id: 'actuallyadditions:crushing/deepslate_lapis_ore' })
    event.remove({ id: 'actuallyadditions:crushing/deepslate_redstone_ore' })
    event.remove({ id: 'actuallyadditions:crushing/coal_ore' })
    event.remove({ id: 'actuallyadditions:crushing/danedlion' })
    event.remove({ id: 'actuallyadditions:crushing/diamond_horse_armor' })
    event.remove({ id: 'actuallyadditions:crushing/glowstone' })
    event.remove({ id: 'actuallyadditions:crushing/golden_horse_armor' })
    event.remove({ id: 'actuallyadditions:crushing/gravel' })
    event.remove({ id: 'actuallyadditions:crushing/iron_horse_armor' })
    event.remove({ id: 'actuallyadditions:crushing/lilac' })
    event.remove({ id: 'actuallyadditions:crushing/lily_of_the_valley' })
    event.remove({ id: 'actuallyadditions:reset/crusher' })
    event.shaped('minecraft:sunflower', ['#A#', 'ABA', '#A#'], { '#': 'kubejs:organic_essence', 'A': 'voidminers:rubetine', 'B': 'kubejs:earth_essence' }).id('kubejsstudio:sunflower')
    event.shaped('laserio:logic_chip_raw', ['#A#', 'BCB', '#A#'], { '#': 'minecraft:redstone', 'A': 'minecraft:gold_nugget', 'B': 'minecraft:clay_ball', 'C': 'mekanism:ingot_osmium' }).id('kubejsstudio:logic_chip_raw')
    event.shaped('draconicevolution:draconium_dust', ['###', 'ABA', '###'], { '#': 'kubejs:ender_essence', 'A': 'minecraft:purple_dye', 'B': 'ae2:fluix_pearl' }).id('kubejsstudio:draconium_dust')
    event.shaped('minecraft:ancient_debris', ['#A#', 'ABA', '#A#'], { '#': 'minecraft:blaze_rod', 'A': 'minecraft:obsidian', 'B': 'minecraft:diamond' }).id('kubejsstudio:ancient_debris')
    event.remove({ id: 'mysticalagriculture:seed/infusion/earth' })
    event.remove({ id: 'mekmm:compat/mysticalagriculture/earth' })
    event.remove({ id: 'mekmm:compat/mysticalagriculture/dye' })
    event.remove({ id: 'mekmm:compat/mysticalagriculture/air' })
    event.remove({ id: 'mekmm:compat/mysticalagriculture/fire' })
    event.remove({ id: 'mekmm:compat/mysticalagriculture/water' })
    event.remove({ id: 'mekmm:compat/ars_nouveau/planting/frostaya_pod' })
    event.remove({ id: 'mekmm:compat/ars_nouveau/planting/mendosteen_pod' })
    event.shaped('mysticalagriculture:earth_seeds', ['#A#', 'BCB', '#A#'], { '#': 'kubejs:organic_essence', 'A': 'allthecompressed:dirt_1x', 'B': 'mysticalagriculture:inferium_block', 'C': 'actuallyadditions:flax_seeds' }).id('kubejsstudio:earth_seeds')
    event.remove({ id: 'jdte:life_apple_infusion' })
    event.shaped('mysticalagriculture:iron_seeds', ['#A#', 'BCB', '#A#'], { '#': 'kubejs:living_essence', 'A': 'minecraft:iron_block', 'B': 'mysticalagriculture:prudentium_block', 'C': 'mysticalagriculture:earth_seeds' }).id('kubejsstudio:iron_seeds')
    event.shaped('mysticalagriculture:prosperity_shard', [' # ', '#A#', ' # '], { '#': 'kubejs:precious_essence', 'A': 'minecraft:lapis_lazuli' }).id('kubejsstudio:prosperity_shard')
    event.shaped('mysticalagriculture:prosperity_ore', ['#A#', 'ABA', '#A#'], { '#': 'mysticalagriculture:inferium_block', 'A': 'minecraft:stone', 'B': 'mysticalagriculture:prosperity_block' }).id('kubejsstudio:prosperity_ore')
    event.shaped('minecraft:amethyst_shard', ['###', 'ABA', '###'], { '#': 'kubejs:precious_essence', 'A': 'minecraft:purple_dye', 'B': 'allthecompressed:glass_1x' }).id('kubejsstudio:amethyst_shard')
    event.remove({ id: 'replication:replicator_enclosure' })
    event.shaped('replication:replicator_enclosure', ['###', '#A#', '###'], { '#': 'minecraft:purple_stained_glass_pane', 'A': 'minecraft:copper_ingot' }).id('kubejsstudio:replicator_enclosure')
    event.remove({ id: 'mekanism:control_circuit/infused_advanced' })
    event.remove({ id: 'mekanism:control_circuit/infused_elite' })
    event.remove({ id: 'mekanism:control_circuit/infused_ultimate' })
    event.remove({ id: 'mekanism_extras:control_circuit/infused_absolute' })
    event.remove({ id: 'mekanism_extras:control_circuit/infused_cosmic' })
    event.remove({ id: 'mekanism_extras:control_circuit/infused_infinite' })
    event.remove({ id: 'mekanism_extras:control_circuit/infused_supreme' })
    event.remove({ id: 'oritech:atomicforge/compat/mekanism/advanced_control_circuit' })
    event.remove({ id: 'oritech:atomicforge/compat/mekanism/basic_control_circuit' })
    event.remove({ id: 'oritech:atomicforge/compat/mekanism/elite_control_circuit' })
    event.remove({ id: 'oritech:atomicforge/compat/mekanism/ultimate_control_circuit' })
    event.remove({ id: 'oritech:foundry/alloy/compat/mekanism/atomic_alloy' })
    event.remove({ id: 'oritech:foundry/alloy/compat/mekanism/infused_alloy' })
    event.remove({ id: 'oritech:foundry/alloy/compat/mekanism/reinforced_alloy' })
    event.shaped('minecraft:emerald', ['###', 'ABA', '###'], { '#': 'minecraft:glowstone_dust', 'A': 'minecraft:green_dye', 'B': 'minecraft:diamond' }).id('kubejsstudio:emerald')
    event.shaped('minecraft:emerald_ore', ['#A#', 'ABA', '#A#'], { '#': 'minecraft:glowstone', 'A': 'minecraft:stone', 'B': 'minecraft:emerald_block' }).id('kubejsstudio:emerald_ore')
    event.shaped('minecraft:soul_sand', ['###', '#A#', '###'], { '#': 'kubejs:nether_essence', 'A': 'minecraft:sand' }).id('kubejsstudio:soul_sand')
    event.remove({ id: 'apotheosis:salvaging/other/chain_armor' })
    event.remove({ id: 'apotheosis:salvaging/other/diamond_armor' })
    event.remove({ id: 'apotheosis:salvaging/other/diamond_horse_armor' })
    event.remove({ id: 'apotheosis:salvaging/other/diamond_tools' })
    event.remove({ id: 'apotheosis:salvaging/other/gold_armor' })
    event.remove({ id: 'apotheosis:salvaging/other/gold_tools' })
    event.remove({ id: 'apotheosis:salvaging/other/golden_horse_armor' })
    event.remove({ id: 'apotheosis:salvaging/other/iron_armor' })
    event.remove({ id: 'apotheosis:salvaging/other/iron_horse_armor' })
    event.remove({ id: 'apotheosis:salvaging/other/iron_tools' })
    event.remove({ id: 'apotheosis:salvaging/other/leather_armor' })
    event.remove({ id: 'apotheosis:salvaging/other/leather_horse_armor' })
    event.remove({ id: 'apotheosis:salvaging/other/netherite_armor' })
    event.remove({ id: 'apotheosis:salvaging/other/netherite_tools' })
    event.remove({ id: 'apotheosis:salvaging/other/stone_tools' })
    event.remove({ id: 'apotheosis:salvaging/other/wolf_armor' })
    event.remove({ id: 'apotheosis:salvaging/other/wooden_tools' })
    event.shaped('mekanism:chemical_dissolution_chamber', ['#A#', 'BCB', '#A#'], { '#': 'mekanism:ingot_refined_obsidian', 'A': 'mekanism:basic_chemical_tank', 'B': 'mekanism:advanced_control_circuit', 'C': 'mekanism:steel_casing' }).id('kubejsstudio:chemical_dissolution_chamber')
    event.shaped('mekmm:planting_station', ['#A#', 'BCB', '#A#'], { '#': 'mekanism:alloy_infused', 'A': 'mekanism:advanced_control_circuit', 'B': 'mekanism:bio_fuel', 'C': 'mekanism:steel_casing' }).id('kubejsstudio:planting_station')
    event.remove({ id: 'mekanism:chemical_dissolution_chamber' })
    event.remove({ id: 'mekmm:planting_station' })
    event.remove({ id: 'oritech:crafting/catalyst' })
    event.remove({ id: 'oritech:crafting/catalyst_alt' })
    event.remove({ id: 'mekanism:upgrade/chemical' })
    event.shaped('minecraft:pointed_dripstone', ['###', 'A#B', ' # '], { '#': 'minecraft:stone', 'A': 'minecraft:lava_bucket', 'B': 'minecraft:water_bucket' }).id('kubejsstudio:pointed_dripstone')
    event.shaped('minecraft:cobbled_deepslate', ['#A#', 'ABA', '#A#'], { '#': 'kubejs:earth_essence', 'A': 'kubejs:precious_essence', 'B': 'allthecompressed:cobblestone_3x' }).id('kubejsstudio:cobbled_deepslate')
    event.shaped('mysticalagriculture:nature_seeds', ['#A#', 'BCD', '#E#'], { '#': 'kubejs:organic_essence', 'A': 'minecraft:wheat_seeds', 'B': 'minecraft:sunflower', 'C': 'mysticalagriculture:earth_seeds', 'D': 'minecraft:rose_bush', 'E': 'actuallyadditions:flax_seeds' }).id('kubejsstudio:nature_seeds')
    event.shaped('oritech:deepslate_platinum_ore', ['#A#', 'BCB', '#A#'], { '#': 'kubejs:precious_essence', 'A': 'minecraft:gold_ingot', 'B': 'oritech:platinum_ingot', 'C': 'minecraft:deepslate' }).id('kubejsstudio:deepslate_platinum_ore')
    event.shaped('oritech:platinum_nugget', ['#A#', 'ABA', '#A#'], { '#': 'mekanism:nugget_osmium', 'A': 'minecraft:gold_nugget', 'B': 'minecraft:deepslate' }).id('kubejsstudio:platinum_nugget')
    event.remove({ id: 'oritech:compat/ae2/charger/fluxite' })
    event.remove({ id: 'oritech:compat/mekanism/infusing/biosteel_dust' })
    event.remove({ id: 'oritech:compat/productivemetalworks/alloying/biosteel' })
    event.remove({ id: 'oritech:compat/productivemetalworks/alloying/duratium' })
    event.remove({ id: 'oritech:compat/productivemetalworks/alloying/adamant' })
    event.remove({ id: 'oritech:compat/productivemetalworks/alloying/energite' })
    event.remove({ id: 'justdirethings:budding_time_amethyst' })
    event.remove({ id: 'oritech:compat/powah/energizing/fluxite' })
    event.remove({ id: 'actuallyadditions:lens_of_the_miner' })
    event.remove({ id: 'botanypots:minecraft/interaction/lava_to_obsidian' })
    event.remove({ id: 'bhc:yellow_heart_canister' })
    event.remove({ id: 'bhc:blue_heart_canister' })
    event.remove({ id: 'bhc:green_heart_canister' })
    event.remove({ id: 'bhc:red_heart_canister' })
    event.shaped('mysticalagriculture:nether_seeds', ['#A#', 'ABA', '#A#'], { '#': 'minecraft:netherrack', 'A': 'minecraft:blaze_powder', 'B': 'minecraft:lava_bucket' }).id('kubejsstudio:nether_seeds')
    event.shaped('mysticalagriculture:end_seeds', ['#A#', 'ABA', '#A#'], { '#': 'minecraft:end_stone', 'A': 'minecraft:ender_pearl', 'B': 'draconicevolution:draconium_ingot' }).id('kubejsstudio:end_seeds')
    event.shaped('minecraft:netherrack', ['###', '#A#', '###'], { '#': 'kubejs:nether_essence', 'A': 'minecraft:stone' }).id('kubejsstudio:netherrack')
    event.shaped('minecraft:end_stone', ['###', '#A#', '###'], { '#': 'kubejs:ender_essence', 'A': 'minecraft:stone' }).id('kubejsstudio:end_stone')
    event.remove({ id: 'botanypots:minecraft/crop/sculk' })
    event.remove({ id: 'botanypots:minecraft/crop/sculk_catalyst' })
    event.remove({ id: 'botanypots:minecraft/crop/sculk_sensor' })
    event.remove({ id: 'botanypots:minecraft/crop/sculk_shrieker' })
    event.remove({ id: 'botanypots:minecraft/crop/sculk_vein' })
    event.remove({ id: 'botanypots:minecraft/soil/sculk' })
    event.remove({ id: 'botanypots:minecraft/soil/sculk_catalyst' })
    event.shaped('minecraft:end_portal_frame', ['###', 'ABA', 'CCC'], { '#': 'kubejs:ender_essence_block', 'A': 'extendedcrafting:enhanced_ender_ingot', 'B': 'minecraft:ender_eye', 'C': 'minecraft:end_stone' }).id('kubejsstudio:end_portal_frame')
    event.shaped(Item.of('kubejs:earth_essence', 9), ['#'], { '#': 'kubejs:earth_essence_block' }).id('kubejsstudio:earth_essence_from_block')
    event.shaped(Item.of('kubejs:precious_essence', 9), ['#'], { '#': 'kubejs:precious_essence_block' }).id('kubejsstudio:precious_essence_from_block')
    event.shaped(Item.of('kubejs:quantum_essence', 9), ['#'], { '#': 'kubejs:quantum_essence_block' }).id('kubejsstudio:quantum_essence_from_block')
    event.shaped(Item.of('kubejs:living_essence', 9), ['#'], { '#': 'kubejs:living_essence_block' }).id('kubejsstudio:living_essence_from_block')
    event.shaped(Item.of('kubejs:ender_essence', 9), ['#'], { '#': 'kubejs:ender_essence_block' }).id('kubejsstudio:ender_essence_from_block')
    event.shaped(Item.of('minecraft:sculk'), [' # ', '#A#', ' # '], { '#': 'minecraft:echo_shard', 'A': 'kubejs:precious_essence_block' }).id('kubejsstudio:sculk')
    event.shaped(Item.of('minecraft:sculk_shrieker'), ['#A#', 'BBB'], { '#': 'minecraft:bone_block', 'A': 'minecraft:echo_shard', 'B': 'minecraft:sculk' }).id('kubejsstudio:sculk_shrieker')
    event.remove({ id: 'functionalstorage:obsidian_upgrade' })
    event.remove({ id: 'extendedcrafting:black_iron_ingot' })
    event.remove({ id: 'productivemetalworks:alloying/molten_steel' })
    event.remove({ id: 'productivemetalworks:alloying/molten_magma_cream' })
    event.remove({ id: 'productivemetalworks:alloying/molten_refined_glowstone' })
    event.remove({ id: 'productivemetalworks:alloying/molten_refined_obsidian' })
    event.remove({ id: 'compactmekanismmachines:compact_fission_reactor' })
    event.remove({ id: 'compactmekanismmachines:compact_industrial_turbine' })
    event.remove({ id: 'compactmekanismmachines:compact_thermal_evaporation' })
    event.remove({ id: 'compactmekanismmachinesplus:compact_fusion_reactor' })
    event.remove({ id: 'compactmekanismmachinesplus:compact_sps' })
    event.remove({ id: 'compactmekanismmachinesplus:compact_thermoelectric_boiler' })
    event.remove({ id: 'industrialforegoing:ore_laser_base' })
    event.remove({ id: 'replicatemekanism:crafting/replica_upgrade_recipe' })
    event.remove({ id: 'mekanism:upgrade/anchor' })
    event.remove({ id: 'ae2:inscriber/logic_processor_print' })
    event.shaped('minecraft:blackstone', ['#A#', 'ABA', '#A#'], { '#': 'kubejs:nether_essence', 'A': 'minecraft:black_dye', 'B': 'minecraft:stone' }).id('kubejsstudio:blackstone')
    event.shaped('mekanism:tin_ore', ['#A#', 'BCB', '#A#'], { '#': 'kubejs:metallic_essence', 'A': 'minecraft:white_dye', 'B': '#c:ingots/tin', 'C': '#minecraft:copper_ores' }).id('kubejsstudio:tin_ore')
    event.shaped('mekanism:nugget_tin', ['#A#', 'B#B', '#A#'], { '#': '#c:nuggets/copper', 'A': 'kubejs:metallic_essence_block', 'B': 'minecraft:white_dye' }).id('kubejsstudio:ingot_tin')
    event.shaped('mekanism:lead_ore', ['#A#', 'BCB', '#A#'], { '#': 'kubejs:metallic_essence_block', 'A': 'minecraft:gray_dye', 'B': '#c:ingots/lead', 'C': '#c:ores/tin' }).id('kubejsstudio:lead_ore')
    event.shaped('mekanism:nugget_lead', ['#A#', 'ABA', '#A#'], { '#': '#c:nuggets/osmium', 'A': '#c:nuggets/copper', 'B': 'kubejs:metallic_essence_block' }).id('kubejsstudio:nugget_lead')
    event.shaped('mekanism:deepslate_uranium_ore', ['#A#', 'BCB', '#A#'], { '#': 'kubejs:metallic_essence_block', 'A': 'minecraft:lime_dye', 'B': '#c:ingots/uranium', 'C': 'minecraft:deepslate' }).id('kubejsstudio:deepslate_uranium_ore')
    event.shaped('mekanism:nugget_uranium', ['#A#', 'A#A', '#A#'], { '#': '#c:nuggets/lead', 'A': '#c:nuggets/platinum' }).id('kubejsstudio:nugget_uranium')
    event.remove({ id: 'avaritia:diamond_lattice' })
    event.remove({ id: 'avaritia:diamond_lattice_normal' })
    event.shapeless('kubejs:earth_essence_block', ['kubejs:earth_essence', 'kubejs:earth_essence', 'kubejs:earth_essence', 'kubejs:earth_essence']).id('kubejsstudio:earth_essence_block')
    event.shapeless('kubejs:organic_essence_block', ['kubejs:organic_essence', 'kubejs:organic_essence', 'kubejs:organic_essence', 'kubejs:organic_essence', 'kubejs:organic_essence', 'kubejs:organic_essence', 'kubejs:organic_essence', 'kubejs:organic_essence', 'kubejs:organic_essence']).id('kubejsstudio:organic_essence_block')
    event.shapeless('kubejs:living_essence_block', ['kubejs:living_essence', 'kubejs:living_essence', 'kubejs:living_essence', 'kubejs:living_essence', 'kubejs:living_essence', 'kubejs:living_essence', 'kubejs:living_essence', 'kubejs:living_essence', 'kubejs:living_essence']).id('kubejsstudio:living_essence_block')
    event.shapeless('kubejs:metallic_essence_block', ['kubejs:metallic_essence', 'kubejs:metallic_essence', 'kubejs:metallic_essence', 'kubejs:metallic_essence']).id('kubejsstudio:metallic_essence_block')
    event.shapeless('kubejs:precious_essence_block', ['kubejs:precious_essence', 'kubejs:precious_essence', 'kubejs:precious_essence', 'kubejs:precious_essence', 'kubejs:precious_essence', 'kubejs:precious_essence', 'kubejs:precious_essence', 'kubejs:precious_essence', 'kubejs:precious_essence']).id('kubejsstudio:precious_essence_block')
    event.shapeless('kubejs:nether_essence_block', ['kubejs:nether_essence', 'kubejs:nether_essence', 'kubejs:nether_essence', 'kubejs:nether_essence', 'kubejs:nether_essence', 'kubejs:nether_essence', 'kubejs:nether_essence', 'kubejs:nether_essence', 'kubejs:nether_essence']).id('kubejsstudio:nether_essence_block')
    event.shapeless('kubejs:ender_essence_block', ['kubejs:ender_essence', 'kubejs:ender_essence', 'kubejs:ender_essence', 'kubejs:ender_essence', 'kubejs:ender_essence', 'kubejs:ender_essence', 'kubejs:ender_essence', 'kubejs:ender_essence', 'kubejs:ender_essence']).id('kubejsstudio:ender_essence_block')
    event.shapeless('kubejs:quantum_essence_block', ['kubejs:quantum_essence', 'kubejs:quantum_essence', 'kubejs:quantum_essence', 'kubejs:quantum_essence', 'kubejs:quantum_essence', 'kubejs:quantum_essence', 'kubejs:quantum_essence', 'kubejs:quantum_essence', 'kubejs:quantum_essence']).id('kubejsstudio:quantum_essence_block')
    event.shaped(Item.of('ars_nouveau:purple_archwood_sapling', 16), ['#A#', 'BCB', '#A#'], { '#': 'minecraft:purple_dye', 'A': 'minecraft:gold_nugget', 'B': 'kubejs:organic_essence', 'C': '#minecraft:saplings' }).id('kubejsstudio:purple_archwood_sapling')
    event.remove({ id: 'mekanism:tier_installer/basic' })
    event.remove({ id: 'mekanism:tier_installer/advanced' })
    event.remove({ id: 'mekanism:tier_installer/elite' })
    event.remove({ id: 'mekanism:tier_installer/ultimate' })
    event.remove({ id: 'mekanism_extras:tier_installer/supreme' })
    event.remove({ id: 'replicatemekanism:crafting/replica_tier_installer_recipe' })
    event.remove({ id: 'mekanism_extras:tier_installer/infinite' })
    event.remove({ id: 'mekanism_extras:tier_installer/cosmic' })
    event.remove({ id: 'mekanism_extras:tier_installer/absolute' })
    event.shaped('minecraft:torchflower_seeds', ['# #', 'ABA', '# #'], { '#': 'kubejs:organic_essence', 'A': '#chipped:torch', 'B': '#c:seeds' }).id('kubejsstudio:torchflower_seeds')
    event.shaped('minecraft:pink_petals', ['###', '#A#', '###'], { '#': 'minecraft:pink_dye', 'A': '#minecraft:flowers' }).id('kubejsstudio:pink_petals')
    event.remove({ id: 'mekanism:processing/uranium/fissile_fuel' })
    event.shaped('minecraft:dirt', ['###', '# #', '###'], { '#': 'kubejs:earth_essence' }).id('kubejsstudio:dirt')
    // kubejsstudio recipes; re-apply merges by recipe id
    event.shapeless(Item.of('kubejs:earth_essence_block', 4), ['kubejs:earth_essence_block_1']).id('kubejsstudio:earth_essence_block_uncraft')
    event.shapeless(Item.of('kubejs:organic_essence_block', 9), ['kubejs:organic_essence_block_1']).id('kubejsstudio:organic_essence_block_uncraft')
    event.shapeless(Item.of('kubejs:living_essence_block', 9), ['kubejs:living_essence_block_1']).id('kubejsstudio:living_essence_block_uncraft')
    event.shapeless(Item.of('kubejs:precious_essence_block', 9), ['kubejs:precious_essence_block_1']).id('kubejsstudio:precious_essence_block_uncraft')
    event.shapeless(Item.of('kubejs:nether_essence_block', 9), ['kubejs:nether_essence_block_1']).id('kubejsstudio:nether_essence_block_uncraft')
    event.shapeless(Item.of('kubejs:ender_essence_block', 9), ['kubejs:ender_essence_block_1']).id('kubejsstudio:ender_essence_block_uncraft')
    event.shapeless(Item.of('kubejs:quantum_essence_block', 9), ['kubejs:quantum_essence_block_1']).id('kubejsstudio:quantum_essence_block_uncraft')
    event.shapeless(Item.of('kubejs:earth_essence_block_1', 9), ['kubejs:earth_essence_block_2']).id('kubejsstudio:earth_essence_block_1_uncraft')
    event.shapeless(Item.of('kubejs:earth_essence_block_2', 9), ['kubejs:earth_essence_block_3']).id('kubejsstudio:earth_essence_block_2_uncraft')
    event.shapeless(Item.of('kubejs:earth_essence_block_3', 9), ['kubejs:earth_essence_block_4']).id('kubejsstudio:earth_essence_block_3_uncraft')
    event.shapeless(Item.of('kubejs:earth_essence_block_4', 9), ['kubejs:earth_essence_block_5']).id('kubejsstudio:earth_essence_block_4_uncraft')
    event.shapeless('kubejs:earth_essence_block_5', ['kubejs:earth_essence_block_4', 'kubejs:earth_essence_block_4', 'kubejs:earth_essence_block_4', 'kubejs:earth_essence_block_4', 'kubejs:earth_essence_block_4', 'kubejs:earth_essence_block_4', 'kubejs:earth_essence_block_4', 'kubejs:earth_essence_block_4', 'kubejs:earth_essence_block_4']).id('kubejsstudio:earth_essence_block_5')
    event.shapeless('kubejs:earth_essence_block_4', ['kubejs:earth_essence_block_3', 'kubejs:earth_essence_block_3', 'kubejs:earth_essence_block_3', 'kubejs:earth_essence_block_3', 'kubejs:earth_essence_block_3', 'kubejs:earth_essence_block_3', 'kubejs:earth_essence_block_3', 'kubejs:earth_essence_block_3', 'kubejs:earth_essence_block_3']).id('kubejsstudio:earth_essence_block_4')
    event.shapeless('kubejs:earth_essence_block_3', ['kubejs:earth_essence_block_2', 'kubejs:earth_essence_block_2', 'kubejs:earth_essence_block_2', 'kubejs:earth_essence_block_2', 'kubejs:earth_essence_block_2', 'kubejs:earth_essence_block_2', 'kubejs:earth_essence_block_2', 'kubejs:earth_essence_block_2', 'kubejs:earth_essence_block_2']).id('kubejsstudio:earth_essence_block_3')
    event.shapeless('kubejs:earth_essence_block_2', ['kubejs:earth_essence_block_1', 'kubejs:earth_essence_block_1', 'kubejs:earth_essence_block_1', 'kubejs:earth_essence_block_1', 'kubejs:earth_essence_block_1', 'kubejs:earth_essence_block_1', 'kubejs:earth_essence_block_1', 'kubejs:earth_essence_block_1', 'kubejs:earth_essence_block_1']).id('kubejsstudio:earth_essence_block_2')
    event.shapeless('kubejs:earth_essence_block_1', ['kubejs:earth_essence_block', 'kubejs:earth_essence_block', 'kubejs:earth_essence_block', 'kubejs:earth_essence_block', 'kubejs:earth_essence_block', 'kubejs:earth_essence_block', 'kubejs:earth_essence_block', 'kubejs:earth_essence_block', 'kubejs:earth_essence_block']).id('kubejsstudio:earth_essence_block_1')
    event.shapeless('kubejs:organic_essence_block_4', ['kubejs:organic_essence_block_3', 'kubejs:organic_essence_block_3', 'kubejs:organic_essence_block_3', 'kubejs:organic_essence_block_3', 'kubejs:organic_essence_block_3', 'kubejs:organic_essence_block_3', 'kubejs:organic_essence_block_3', 'kubejs:organic_essence_block_3', 'kubejs:organic_essence_block_3']).id('kubejsstudio:organic_essence_block_4')
    event.shapeless('kubejs:organic_essence_block_3', ['kubejs:organic_essence_block_2', 'kubejs:organic_essence_block_2', 'kubejs:organic_essence_block_2', 'kubejs:organic_essence_block_2', 'kubejs:organic_essence_block_2', 'kubejs:organic_essence_block_2', 'kubejs:organic_essence_block_2', 'kubejs:organic_essence_block_2', 'kubejs:organic_essence_block_2']).id('kubejsstudio:organic_essence_block_3')
    event.shapeless('kubejs:organic_essence_block_2', ['kubejs:organic_essence_block_1', 'kubejs:organic_essence_block_1', 'kubejs:organic_essence_block_1', 'kubejs:organic_essence_block_1', 'kubejs:organic_essence_block_1', 'kubejs:organic_essence_block_1', 'kubejs:organic_essence_block_1', 'kubejs:organic_essence_block_1', 'kubejs:organic_essence_block_1']).id('kubejsstudio:organic_essence_block_2')
    event.shapeless('kubejs:organic_essence_block_1', ['kubejs:organic_essence_block', 'kubejs:organic_essence_block', 'kubejs:organic_essence_block', 'kubejs:organic_essence_block', 'kubejs:organic_essence_block', 'kubejs:organic_essence_block', 'kubejs:organic_essence_block', 'kubejs:organic_essence_block', 'kubejs:organic_essence_block']).id('kubejsstudio:organic_essence_block_1')
    event.shapeless('kubejs:organic_essence_block_5', ['kubejs:organic_essence_block_4', 'kubejs:organic_essence_block_4', 'kubejs:organic_essence_block_4', 'kubejs:organic_essence_block_4', 'kubejs:organic_essence_block_4', 'kubejs:organic_essence_block_4', 'kubejs:organic_essence_block_4', 'kubejs:organic_essence_block_4', 'kubejs:organic_essence_block_4']).id('kubejsstudio:organic_essence_block_5')
    event.shapeless('kubejs:living_essence_block_5', ['kubejs:living_essence_block_4', 'kubejs:living_essence_block_4', 'kubejs:living_essence_block_4', 'kubejs:living_essence_block_4', 'kubejs:living_essence_block_4', 'kubejs:living_essence_block_4', 'kubejs:living_essence_block_4', 'kubejs:living_essence_block_4', 'kubejs:living_essence_block_4']).id('kubejsstudio:living_essence_block_5')
    event.shapeless('kubejs:living_essence_block_4', ['kubejs:living_essence_block_3', 'kubejs:living_essence_block_3', 'kubejs:living_essence_block_3', 'kubejs:living_essence_block_3', 'kubejs:living_essence_block_3', 'kubejs:living_essence_block_3', 'kubejs:living_essence_block_3', 'kubejs:living_essence_block_3', 'kubejs:living_essence_block_3']).id('kubejsstudio:living_essence_block_4')
    event.shapeless('kubejs:living_essence_block_3', ['kubejs:living_essence_block_2', 'kubejs:living_essence_block_2', 'kubejs:living_essence_block_2', 'kubejs:living_essence_block_2', 'kubejs:living_essence_block_2', 'kubejs:living_essence_block_2', 'kubejs:living_essence_block_2', 'kubejs:living_essence_block_2', 'kubejs:living_essence_block_2']).id('kubejsstudio:living_essence_block_3')
    event.shapeless('kubejs:living_essence_block_2', ['kubejs:living_essence_block_1', 'kubejs:living_essence_block_1', 'kubejs:living_essence_block_1', 'kubejs:living_essence_block_1', 'kubejs:living_essence_block_1', 'kubejs:living_essence_block_1', 'kubejs:living_essence_block_1', 'kubejs:living_essence_block_1', 'kubejs:living_essence_block_1']).id('kubejsstudio:living_essence_block_2')
    event.shapeless('kubejs:living_essence_block_1', ['kubejs:living_essence_block', 'kubejs:living_essence_block', 'kubejs:living_essence_block', 'kubejs:living_essence_block', 'kubejs:living_essence_block', 'kubejs:living_essence_block', 'kubejs:living_essence_block', 'kubejs:living_essence_block', 'kubejs:living_essence_block']).id('kubejsstudio:living_essence_block_1')
    event.shapeless(Item.of('kubejs:organic_essence_block_4', 9), ['kubejs:organic_essence_block_5']).id('kubejsstudio:organic_essence_block_4_uncraft')
    event.shapeless(Item.of('kubejs:organic_essence_block_3', 9), ['kubejs:organic_essence_block_4']).id('kubejsstudio:organic_essence_block_3_uncraft')
    event.shapeless(Item.of('kubejs:organic_essence_block_2', 9), ['kubejs:organic_essence_block_3']).id('kubejsstudio:organic_essence_block_2_uncraft')
    event.shapeless(Item.of('kubejs:organic_essence_block_1', 9), ['kubejs:organic_essence_block_2']).id('kubejsstudio:organic_essence_block_1_uncraft')
    event.shapeless(Item.of('kubejs:living_essence_block_4', 9), ['kubejs:living_essence_block_5']).id('kubejsstudio:living_essence_block_4_uncraft')
    event.shapeless(Item.of('kubejs:living_essence_block_3', 9), ['kubejs:living_essence_block_4']).id('kubejsstudio:living_essence_block_3_uncraft')
    event.shapeless(Item.of('kubejs:living_essence_block_2', 9), ['kubejs:living_essence_block_3']).id('kubejsstudio:living_essence_block_2_uncraft')
    event.shapeless(Item.of('kubejs:living_essence_block_1', 9), ['kubejs:living_essence_block_2']).id('kubejsstudio:living_essence_block_1_uncraft')
    event.shapeless('kubejs:metallic_essence_block_4', ['kubejs:metallic_essence_block_3', 'kubejs:metallic_essence_block_3', 'kubejs:metallic_essence_block_3', 'kubejs:metallic_essence_block_3', 'kubejs:metallic_essence_block_3', 'kubejs:metallic_essence_block_3', 'kubejs:metallic_essence_block_3', 'kubejs:metallic_essence_block_3', 'kubejs:metallic_essence_block_3']).id('kubejsstudio:metallic_essence_block_4')
    event.shapeless('kubejs:metallic_essence_block_3', ['kubejs:metallic_essence_block_2', 'kubejs:metallic_essence_block_2', 'kubejs:metallic_essence_block_2', 'kubejs:metallic_essence_block_2', 'kubejs:metallic_essence_block_2', 'kubejs:metallic_essence_block_2', 'kubejs:metallic_essence_block_2', 'kubejs:metallic_essence_block_2', 'kubejs:metallic_essence_block_2']).id('kubejsstudio:metallic_essence_block_3')
    event.shapeless('kubejs:metallic_essence_block_2', ['kubejs:metallic_essence_block_1', 'kubejs:metallic_essence_block_1', 'kubejs:metallic_essence_block_1', 'kubejs:metallic_essence_block_1', 'kubejs:metallic_essence_block_1', 'kubejs:metallic_essence_block_1', 'kubejs:metallic_essence_block_1', 'kubejs:metallic_essence_block_1', 'kubejs:metallic_essence_block_1']).id('kubejsstudio:metallic_essence_block_2')
    event.shapeless('kubejs:metallic_essence_block_1', ['kubejs:metallic_essence_block', 'kubejs:metallic_essence_block', 'kubejs:metallic_essence_block', 'kubejs:metallic_essence_block', 'kubejs:metallic_essence_block', 'kubejs:metallic_essence_block', 'kubejs:metallic_essence_block', 'kubejs:metallic_essence_block', 'kubejs:metallic_essence_block']).id('kubejsstudio:metallic_essence_block_1')
    event.shapeless('kubejs:metallic_essence_block_5', ['kubejs:metallic_essence_block_4', 'kubejs:metallic_essence_block_4', 'kubejs:metallic_essence_block_4', 'kubejs:metallic_essence_block_4', 'kubejs:metallic_essence_block_4', 'kubejs:metallic_essence_block_4', 'kubejs:metallic_essence_block_4', 'kubejs:metallic_essence_block_4', 'kubejs:metallic_essence_block_4']).id('kubejsstudio:metallic_essence_block_5')
    event.shapeless(Item.of('kubejs:metallic_essence_block', 4), ['kubejs:metallic_essence_block_1']).id('kubejsstudio:metallic_essence_block_uncraft')
    event.shapeless(Item.of('kubejs:metallic_essence_block_1', 9), ['kubejs:metallic_essence_block_2']).id('kubejsstudio:metallic_essence_block_1_uncraft')
    event.shapeless(Item.of('kubejs:metallic_essence_block_2', 9), ['kubejs:metallic_essence_block_3']).id('kubejsstudio:metallic_essence_block_2_uncraft')
    event.shapeless(Item.of('kubejs:metallic_essence_block_3', 9), ['kubejs:metallic_essence_block_4']).id('kubejsstudio:metallic_essence_block_3_uncraft')
    event.shapeless(Item.of('kubejs:metallic_essence_block_4', 9), ['kubejs:metallic_essence_block_5']).id('kubejsstudio:metallic_essence_block_4_uncraft')
    event.shapeless(Item.of('kubejs:precious_essence_block_4', 9), ['kubejs:precious_essence_block_5']).id('kubejsstudio:precious_essence_block_4_uncraft')
    event.shapeless(Item.of('kubejs:precious_essence_block_3', 9), ['kubejs:precious_essence_block_4']).id('kubejsstudio:precious_essence_block_3_uncraft')
    event.shapeless(Item.of('kubejs:precious_essence_block_2', 9), ['kubejs:precious_essence_block_3']).id('kubejsstudio:precious_essence_block_2_uncraft')
    event.shapeless(Item.of('kubejs:precious_essence_block_1', 9), ['kubejs:precious_essence_block_2']).id('kubejsstudio:precious_essence_block_1_uncraft')
    event.shapeless('kubejs:precious_essence_block_5', ['kubejs:precious_essence_block_4', 'kubejs:precious_essence_block_4', 'kubejs:precious_essence_block_4', 'kubejs:precious_essence_block_4', 'kubejs:precious_essence_block_4', 'kubejs:precious_essence_block_4', 'kubejs:precious_essence_block_4', 'kubejs:precious_essence_block_4', 'kubejs:precious_essence_block_4']).id('kubejsstudio:precious_essence_block_5')
    event.shapeless('kubejs:precious_essence_block_4', ['kubejs:precious_essence_block_3', 'kubejs:precious_essence_block_3', 'kubejs:precious_essence_block_3', 'kubejs:precious_essence_block_3', 'kubejs:precious_essence_block_3', 'kubejs:precious_essence_block_3', 'kubejs:precious_essence_block_3', 'kubejs:precious_essence_block_3', 'kubejs:precious_essence_block_3']).id('kubejsstudio:precious_essence_block_4')
    event.shapeless('kubejs:precious_essence_block_3', ['kubejs:precious_essence_block_2', 'kubejs:precious_essence_block_2', 'kubejs:precious_essence_block_2', 'kubejs:precious_essence_block_2', 'kubejs:precious_essence_block_2', 'kubejs:precious_essence_block_2', 'kubejs:precious_essence_block_2', 'kubejs:precious_essence_block_2', 'kubejs:precious_essence_block_2']).id('kubejsstudio:precious_essence_block_3')
    event.shapeless('kubejs:precious_essence_block_2', ['kubejs:precious_essence_block_1', 'kubejs:precious_essence_block_1', 'kubejs:precious_essence_block_1', 'kubejs:precious_essence_block_1', 'kubejs:precious_essence_block_1', 'kubejs:precious_essence_block_1', 'kubejs:precious_essence_block_1', 'kubejs:precious_essence_block_1', 'kubejs:precious_essence_block_1']).id('kubejsstudio:precious_essence_block_2')
    event.shapeless('kubejs:precious_essence_block_1', ['kubejs:precious_essence_block', 'kubejs:precious_essence_block', 'kubejs:precious_essence_block', 'kubejs:precious_essence_block', 'kubejs:precious_essence_block', 'kubejs:precious_essence_block', 'kubejs:precious_essence_block', 'kubejs:precious_essence_block', 'kubejs:precious_essence_block']).id('kubejsstudio:precious_essence_block_1')
    event.shapeless('kubejs:nether_essence_block_5', ['kubejs:nether_essence_block_4', 'kubejs:nether_essence_block_4', 'kubejs:nether_essence_block_4', 'kubejs:nether_essence_block_4', 'kubejs:nether_essence_block_4', 'kubejs:nether_essence_block_4', 'kubejs:nether_essence_block_4', 'kubejs:nether_essence_block_4', 'kubejs:nether_essence_block_4']).id('kubejsstudio:nether_essence_block_5')
    event.shapeless('kubejs:nether_essence_block_4', ['kubejs:nether_essence_block_3', 'kubejs:nether_essence_block_3', 'kubejs:nether_essence_block_3', 'kubejs:nether_essence_block_3', 'kubejs:nether_essence_block_3', 'kubejs:nether_essence_block_3', 'kubejs:nether_essence_block_3', 'kubejs:nether_essence_block_3', 'kubejs:nether_essence_block_3']).id('kubejsstudio:nether_essence_block_4')
    event.shapeless('kubejs:nether_essence_block_3', ['kubejs:nether_essence_block_2', 'kubejs:nether_essence_block_2', 'kubejs:nether_essence_block_2', 'kubejs:nether_essence_block_2', 'kubejs:nether_essence_block_2', 'kubejs:nether_essence_block_2', 'kubejs:nether_essence_block_2', 'kubejs:nether_essence_block_2', 'kubejs:nether_essence_block_2']).id('kubejsstudio:nether_essence_block_3')
    event.shapeless('kubejs:nether_essence_block_2', ['kubejs:nether_essence_block_1', 'kubejs:nether_essence_block_1', 'kubejs:nether_essence_block_1', 'kubejs:nether_essence_block_1', 'kubejs:nether_essence_block_1', 'kubejs:nether_essence_block_1', 'kubejs:nether_essence_block_1', 'kubejs:nether_essence_block_1', 'kubejs:nether_essence_block_1']).id('kubejsstudio:nether_essence_block_2')
    event.shapeless('kubejs:nether_essence_block_1', ['kubejs:nether_essence_block', 'kubejs:nether_essence_block', 'kubejs:nether_essence_block', 'kubejs:nether_essence_block', 'kubejs:nether_essence_block', 'kubejs:nether_essence_block', 'kubejs:nether_essence_block', 'kubejs:nether_essence_block', 'kubejs:nether_essence_block']).id('kubejsstudio:nether_essence_block_1')
    event.shapeless(Item.of('kubejs:nether_essence_block_4', 9), ['kubejs:nether_essence_block_5']).id('kubejsstudio:nether_essence_block_4_uncraft')
    event.shapeless(Item.of('kubejs:nether_essence_block_3', 9), ['kubejs:nether_essence_block_4']).id('kubejsstudio:nether_essence_block_3_uncraft')
    event.shapeless(Item.of('kubejs:nether_essence_block_2', 9), ['kubejs:nether_essence_block_3']).id('kubejsstudio:nether_essence_block_2_uncraft')
    event.shapeless(Item.of('kubejs:nether_essence_block_1', 9), ['kubejs:nether_essence_block_2']).id('kubejsstudio:nether_essence_block_1_uncraft')
    event.shapeless('kubejs:ender_essence_block_5', ['kubejs:ender_essence_block_4', 'kubejs:ender_essence_block_4', 'kubejs:ender_essence_block_4', 'kubejs:ender_essence_block_4', 'kubejs:ender_essence_block_4', 'kubejs:ender_essence_block_4', 'kubejs:ender_essence_block_4', 'kubejs:ender_essence_block_4', 'kubejs:ender_essence_block_4']).id('kubejsstudio:ender_essence_block_5')
    event.shapeless('kubejs:ender_essence_block_4', ['kubejs:ender_essence_block_3', 'kubejs:ender_essence_block_3', 'kubejs:ender_essence_block_3', 'kubejs:ender_essence_block_3', 'kubejs:ender_essence_block_3', 'kubejs:ender_essence_block_3', 'kubejs:ender_essence_block_3', 'kubejs:ender_essence_block_3', 'kubejs:ender_essence_block_3']).id('kubejsstudio:ender_essence_block_4')
    event.shapeless('kubejs:ender_essence_block_3', ['kubejs:ender_essence_block_2', 'kubejs:ender_essence_block_2', 'kubejs:ender_essence_block_2', 'kubejs:ender_essence_block_2', 'kubejs:ender_essence_block_2', 'kubejs:ender_essence_block_2', 'kubejs:ender_essence_block_2', 'kubejs:ender_essence_block_2', 'kubejs:ender_essence_block_2']).id('kubejsstudio:ender_essence_block_3')
    event.shapeless('kubejs:ender_essence_block_2', ['kubejs:ender_essence_block_1', 'kubejs:ender_essence_block_1', 'kubejs:ender_essence_block_1', 'kubejs:ender_essence_block_1', 'kubejs:ender_essence_block_1', 'kubejs:ender_essence_block_1', 'kubejs:ender_essence_block_1', 'kubejs:ender_essence_block_1', 'kubejs:ender_essence_block_1']).id('kubejsstudio:ender_essence_block_2')
    event.shapeless('kubejs:ender_essence_block_1', ['kubejs:ender_essence_block', 'kubejs:ender_essence_block', 'kubejs:ender_essence_block', 'kubejs:ender_essence_block', 'kubejs:ender_essence_block', 'kubejs:ender_essence_block', 'kubejs:ender_essence_block', 'kubejs:ender_essence_block', 'kubejs:ender_essence_block']).id('kubejsstudio:ender_essence_block_1')
    event.shapeless(Item.of('kubejs:ender_essence_block_4', 9), ['kubejs:ender_essence_block_5']).id('kubejsstudio:ender_essence_block_4_uncraft')
    event.shapeless(Item.of('kubejs:ender_essence_block_3', 9), ['kubejs:ender_essence_block_4']).id('kubejsstudio:ender_essence_block_3_uncraft')
    event.shapeless(Item.of('kubejs:ender_essence_block_2', 9), ['kubejs:ender_essence_block_3']).id('kubejsstudio:ender_essence_block_2_uncraft')
    event.shapeless(Item.of('kubejs:ender_essence_block_1', 9), ['kubejs:ender_essence_block_2']).id('kubejsstudio:ender_essence_block_1_uncraft')
    event.shapeless(Item.of('kubejs:quantum_essence_block_4', 9), ['kubejs:quantum_essence_block_5']).id('kubejsstudio:quantum_essence_block_4_uncraft')
    event.shapeless(Item.of('kubejs:quantum_essence_block_3', 9), ['kubejs:quantum_essence_block_4']).id('kubejsstudio:quantum_essence_block_3_uncraft')
    event.shapeless(Item.of('kubejs:quantum_essence_block_2', 9), ['kubejs:quantum_essence_block_3']).id('kubejsstudio:quantum_essence_block_2_uncraft')
    event.shapeless(Item.of('kubejs:quantum_essence_block_1', 9), ['kubejs:quantum_essence_block_2']).id('kubejsstudio:quantum_essence_block_1_uncraft')
})

