StartupEvents.registry('block', MR => {
  
//Earth
MR.create('earth_essence_block')
    .displayName('Block of Earth Essence')
    .soundType('metal')
    .hardness(2.0)
    .resistance(8.0)
  	.requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('c:storage_blocks')
    .tagBlock('c:storage_blocks/earth')
    .texture('kubejs:block/matter/earth_matter_block')

MR.create('earth_essence_block_1')
    .displayName('1x Block of Earth Essence')
    .soundType('metal')
    .hardness(2.0)
    .resistance(8.0)
  	.requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('c:storage_blocks')
    .tagBlock('c:storage_blocks/earth')
    .texture('kubejs:block/matter/earth_matter_block')

MR.create('earth_essence_block_2')
    .displayName('2x Block of Earth Essence')
    .soundType('metal')
    .hardness(2.0)
    .resistance(8.0)
  	.requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('c:storage_blocks')
    .tagBlock('c:storage_blocks/earth')
    .texture('kubejs:block/matter/earth_matter_block')

MR.create('earth_essence_block_3')
    .displayName('3x Block of Earth Essence')
    .soundType('metal')
    .hardness(2.0)
    .resistance(8.0)
  	.requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('c:storage_blocks')
    .tagBlock('c:storage_blocks/earth')
    .texture('kubejs:block/matter/earth_matter_block')

MR.create('earth_essence_block_4')
    .displayName('4x Block of Earth Essence')
    .soundType('metal')
    .hardness(2.0)
    .resistance(8.0)
  	.requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('c:storage_blocks')
    .tagBlock('c:storage_blocks/earth')
    .texture('kubejs:block/matter/earth_matter_block')

MR.create('earth_essence_block_5')
    .displayName('5x Block of Earth Essence')
    .soundType('metal')
    .hardness(2.0)
    .resistance(8.0)
  	.requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .tagBlock('c:storage_blocks')
    .tagBlock('c:storage_blocks/earth')
    .texture('kubejs:block/matter/earth_matter_block')
});
 