#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Sep 06 01:58:19 EDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=FastPBR_v2.0.zip
